# ################################################ #
# Fully versioned R stack for GIS/spatial analysis #
# ################################################ #

FROM mhermans/rversioned:1.O.O

MAINTAINER "Maarten Hermans" maarten@mhermans.net


