# ############################################################# #
# Fully versioned R container with Rstudio + tidyverse packages #
# ############################################################# #

# Start from versioned Rocker image with R at a specific version, plus Rstudio
#
# 0.0.1

FROM rocker/rstudio:3.4.1

MAINTAINER "Maarten Hermans" maarten@mhermans.net

# Specify exact versions for required libraries using apt-get
RUN apt-get update -qq && apt-get -y --no-install-recommends install \
     libimage-exiftool-perl=10.40-1 \
     libmagick++-dev=8:6.9.7.4+dfsg-11+deb9u1 \

     # tmap: proj, gdal, geos 
     libudunits2-dev=2.2.20-1+b1 \
     libv8-3.14-dev=3.14.5.8-11 \  
     libproj-dev=4.9.3-1 \
     libgdal-dev=2.1.2+dfsg-5 \
     libgeos-dev=3.5.1-3 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/ \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds


# install the versions library, that can install specific versions of packages
# using the MRAN service https://mran.microsoft.com/
RUN R -e "install.packages(c('versions'))"

# Install additional R-libraries using the versions library

# Install tidyverse packages https://github.com/tidyverse/tidyverse
RUN R -e "library(versions); \
          install.versions('ggplot2', '2.2.1'); \
          install.versions('dplyr', '0.7.0'); \
          install.versions('tidyr', '0.6.3'); \
          install.versions('readr', '1.1.1'); \
          install.versions('purrr', '0.2.2.2'); \
          install.versions('tibble', '1.3.3'); \
          install.versions('hms', '0.3'); \
          install.versions('stringr', '1.2.0'); \
          install.versions('lubridate', '1.6.0'); \
          install.versions('forcats', '0.2.0'); \
          install.versions('feather', '0.3.1'); \
          install.versions('haven', '1.1.0'); \
          install.versions('httr', '1.2.1'); \
          install.versions('jsonlite', '1.5'); \
          install.versions('readxl', '1.0.0'); \
          install.versions('rvest', '0.3.2'); \
          install.versions('xml2', '1.1.1'); \
          install.versions('modelr', '0.1.0'); \
          install.versions('broom', '0.4.2')"

# Commonly used additional packages
RUN R -e "library(versions); \
          install.versions('assertr', '2.0.2.2'); \
          install.versions('ggrepel', '0.6.5'); \
          #install.versions('tmap', '1.10'); \
          install.versions('likert', '1.3.5'); \
          install.versions('directlabels', '2017.03.31'); \
          install.versions('countrycode', '0.19'); \
          install.versions('survey', '3.32-1'); \
          install.versions('openxlsx', '4.0.17'); \
          install.versions('ggthemes', '3.4.0'); \
          install.versions('futile.logger', '1.4.3'); \
          install.versions('fst', '0.7.2')"


# Commonly used additional packages
RUN R -e "library(versions); \
          install.versions('tmap', '1.10')"

# Define enviroment vars through included dotfiles
COPY .Renviron /home/rstudio/.Renviron
COPY .gitconfig /home/rstudio/.gitconfig

# Set the home directory to the rstudio default user ('rstudio'/'rstudio' login)
WORKDIR /home/rstudio/

# build docker image:
# docker build -t mhermans/rversioned:0.0.1 --file Dockerfile .

# run docker image (localhost:8787):
# docker run -d -v $HOME/var/data:/home/rstudio/data -p 8787:8787 mhermans/rversioned
