# ############################################################# #
# Fully versioned R container with Rstudio + tidyverse packages #
# ############################################################# #

# Start from versioned Rocker image with R at a specific version, plus Rstudio
# 0.1.3
#
# 0.1.2
# R version from 3.5.0 to 3.5.1 
# + janitor package 1.0.0
# + hera package 0.1
# major upgrade ggplot to 3.0.0
# 

#TODO: aanvulling of afsplutsing met packages effects coin pscl [statiek / regressietests ed.]
#TODO: caTools is nodig voor Rstudio notebooks te compilen

# 3.4.4 uses FROM debian:stretch as OS base
FROM rocker/rstudio:3.5.1

MAINTAINER "Maarten Hermans" maarten@mhermans.net

# Specify exact versions for required libraries using apt-get
RUN apt-get update -qq && apt-get -y --no-install-recommends install \
     libimage-exiftool-perl=10.40-1 \
     libmagick++-dev=8:6.9.7.4+dfsg-11+deb9u4 \
    
     # JSON processor, for package jqr (used by?)
     libjq-dev=1.5+dfsg-1.3 \ 
     protobuf-compiler=3.0.0-9 \

     # protocol buffers lib, for package protolite (used by?)
     libprotobuf-dev=3.0.0-9 \

     # tmap: proj, gdal, geos 
     libudunits2-dev=2.2.20-1+b1 \
     libv8-3.14-dev=3.14.5.8-11 \  
     libproj-dev=4.9.3-1 \
     libgdal-dev=2.1.2+dfsg-5 \
     libgeos-dev=3.5.1-3 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/ \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds


# install the versions library, that can install specific versions of packages
# using the MRAN service https://mran.microsoft.com/
RUN R -e "install.packages(c('versions'))"

# Install additional R-libraries using the versions library

RUN R -e "library(versions); \
          install.versions('Rcpp', '0.12.17')"


# Install tidyverse packages https://github.com/tidyverse/tidyverse
RUN R -e "library(versions); \
          install.versions('ggplot2', '3.0.0'); \
          install.versions('dplyr', '0.7.5'); \
          install.versions('tidyr', '0.8.1'); \
          install.versions('readr', '1.1.1'); \
          install.versions('purrr', '0.2.5'); \
          install.versions('tibble', '1.4.2'); \
          install.versions('hms', '0.4.2'); \
          install.versions('stringr', '1.3.1'); \
          install.versions('lubridate', '1.7.4'); \
          install.versions('forcats', '0.3.0'); \
          install.versions('feather', '0.3.1'); \
          install.versions('haven', '1.1.1'); \
          install.versions('httr', '1.3.1'); \
          install.versions('jsonlite', '1.5'); \
          install.versions('readxl', '1.0.0'); \
          install.versions('rvest', '0.3.2'); \
          install.versions('xml2', '1.2.0'); \
          install.versions('modelr', '0.1.1'); \
          install.versions('broom', '0.4.3')"

# Commonly used additional packages
RUN R -e "library(versions); \
          install.versions('assertr', '2.5'); \
          install.versions('janitor', '1.0.0'); \
          install.versions('here', '0.1'); \
          install.versions('ggrepel', '0.8.0'); \
          install.versions('likert', '1.3.5'); \
          install.versions('directlabels', '2018.05.22'); \
          install.versions('countrycode', '1.00.0'); \
          install.versions('survey', '3.33-2'); \
          install.versions('openxlsx', '4.1.0'); \
          install.versions('ggthemes', '3.5.0'); \
          install.versions('futile.logger', '1.4.3')"


# Commonly used additional packages
RUN R -e "library(versions); \
          install.versions('ggalt', '0.4.0'); \
          install.versions('fst', '0.8.6'); \
          install.versions('cowplot', '0.9.2'); \
          install.versions('ggridges', '0.5.0'); \
          install.versions('srvyr', '0.3.3'); \
          install.versions('cartography', '2.1.0'); \
          install.versions('hrbrthemes', '0.5.0'); \
          install.versions('MplusAutomation', '0.7-2'); \
          install.versions('tmap', '1.11-2')"

# quid versioning packages outside of CRAN?
RUN R -e "install.packages('BelgiumMaps.StatBel', repos = 'http://www.datatailor.be/rcube', type = 'source')"

# Define enviroment vars through included dotfiles
COPY .Renviron /home/rstudio/.Renviron
COPY .gitconfig /home/rstudio/.gitconfig

# Set the home directory to the rstudio default user ('rstudio'/'rstudio' login)
WORKDIR /home/rstudio/

